#!/bin/sh
APPDIR=`dirname $0`;
java32  -Xmx512M -cp "$APPDIR/src:$APPDIR/bin:/opt/gwt-linux/gwt-user.jar:/opt/gwt-linux/gwt-dev-linux.jar" com.google.gwt.dev.HostedMode -startupUrl GWTPhotoAlbum.html de.eckhartarnold.PhotoViewer;

