function GWTPhotoAlbum_xs(){var M='',vc='\n-',tb='" for "gwt:onLoadErrorFn"',rb='" for "gwt:onPropertyErrorFn"',ic='"<script src=\\"',fb='"><\/script>',W='#',xb='&',uc=');',mc='-\n',wc='-><\/scr',fc='../GWTPhotoAlbum.css',jc='.cache.js\\"><\/scr" + "ipt>"',Y='/',Tb='00FDE08169CD190B10803FC80ABA35C8',Vb='10C65A27B60007BEC5A0AB2C7D8C553F',Wb='371EE6ABD8A3814CDF8A8FCC229388AE',Xb='418BB2BD687796B12AE1F8375A9AF303',$b=':',lb='::',kc='<scr',eb='<script id="',ob='=',X='?',Yb='ABA909C7DA97E2559944E42898A4D356',Fb='ActiveXObject',qb='Bad handler "',Gb='ChromeTab.ChromeFrame',Pb='Cross-site hosted mode not yet implemented. See issue ',gc='DOMContentLoaded',Zb='EEC7016F0623CF6CC1AF8ABC1F74D074',N='GWTPhotoAlbum_xs',bb='GWTPhotoAlbum_xs.nocache.js',kb='GWTPhotoAlbum_xs::',gb='SCRIPT',Ab='Unexpected exception in locale detection, using default: ',zb='_',yb='__gwt_Locale',db='__gwt_marker_GWTPhotoAlbum_xs',hb='base',_='baseUrl',Q='begin',P='bootstrap',Eb='chromeframe',$='clear.cache.gif',nb='content',Sb='de',vb='default',tc='document.write(',Ub='en',V='end',pc='evtGroup: "loadExternalRefs", millis:(new Date()).getTime(),',rc='evtGroup: "moduleStartup", millis:(new Date()).getTime(),',Mb='gecko',Nb='gecko1_8',R='gwt.codesvr=',S='gwt.hosted=',T='gwt.hybrid',_b='gwt/chrome/chrome.css',sb='gwt:onLoadErrorFn',pb='gwt:onPropertyErrorFn',mb='gwt:property',ec='head',dc='href',Qb='http://code.google.com/p/google-web-toolkit/issues/detail?id=2079',Lb='ie6',Kb='ie8',Jb='ie9',Z='img',xc='ipt>',lc='ipt><!-',ac='link',hc='loadExternalRefs',ub='locale',wb='locale=',ib='meta',oc='moduleName:"GWTPhotoAlbum_xs", sessionId:window.__gwtStatsSessionId, subSystem:"startup",',U='moduleStartup',Ib='msie',jb='name',Cb='opera',bc='rel',Hb='safari',ab='script',Rb='selectingPermutation',O='startup',cc='stylesheet',qc='type: "end"});',sc='type: "moduleRequested"});',cb='undefined',Ob='unknown',Bb='user.agent',Db='webkit',nc='window.__gwtStatsEvent && window.__gwtStatsEvent({';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r=M,s={},t=[],u=[],v=[],w=0,x,y;n&&n({moduleName:N,sessionId:o,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:Q});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function z(){var b=false;try{var c=l.location.search;return (c.indexOf(R)!=-1||(c.indexOf(S)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(T)==-1}catch(a){}z=function(){return b};return b}
function A(){if(p&&q){p(x,N,r,w);n&&n({moduleName:N,sessionId:o,subSystem:O,evtGroup:U,millis:(new Date).getTime(),type:V})}}
function B(){function e(a){var b=a.lastIndexOf(W);if(b==-1){b=a.length}var c=a.indexOf(X);if(c==-1){c=a.length}var d=a.lastIndexOf(Y,Math.min(c,b));return d>=0?a.substring(0,d+1):M}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(Z);b.src=a+$;a=e(b.src)}return a}
function g(){var a=E(_);if(a!=null){return a}return M}
function h(){var a=m.getElementsByTagName(ab);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(bb)!=-1){return e(a[b].src)}}return M}
function i(){var a;if(typeof isBodyLoaded==cb||!isBodyLoaded()){var b=db;var c;m.write(eb+b+fb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=gb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return M}
function j(){var a=m.getElementsByTagName(hb);if(a.length>0){return a[a.length-1].href}return M}
var k=g();if(k==M){k=h()}if(k==M){k=i()}if(k==M){k=j()}if(k==M){k=e(m.location.href)}k=f(k);r=k;return k}
function C(){var b=document.getElementsByTagName(ib);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(jb),g;if(f){f=f.replace(kb,M);if(f.indexOf(lb)>=0){continue}if(f==mb){g=e.getAttribute(nb);if(g){var h,i=g.indexOf(ob);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=M}s[f]=h}}else if(f==pb){g=e.getAttribute(nb);if(g){try{y=eval(g)}catch(a){alert(qb+g+rb)}}}else if(f==sb){g=e.getAttribute(nb);if(g){try{x=eval(g)}catch(a){alert(qb+g+tb)}}}}}}
function D(a,b){return b in t[a]}
function E(a){var b=s[a];return b==null?null:b}
function F(a,b){var c=v;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=u[a](),c=t[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(y){y(a,d,b)}throw null}
u[ub]=function(){var b=null;var c=vb;try{if(!b){var d=location.search;var e=d.indexOf(wb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(xb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=E(ub)}if(!b){b=l[yb]}if(b){c=b}while(b&&!D(ub,b)){var h=b.lastIndexOf(zb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Ab+a)}l[yb]=c;return b||vb};t[ub]={de:0,'default':1,en:2};u[Bb]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(Cb)!=-1}())return Cb;if(function(){return c.indexOf(Db)!=-1||function(){if(c.indexOf(Eb)!=-1){return true}if(typeof window[Fb]!=cb){try{var b=new ActiveXObject(Gb);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Hb;if(function(){return c.indexOf(Ib)!=-1&&m.documentMode>=9}())return Jb;if(function(){return c.indexOf(Ib)!=-1&&m.documentMode>=8}())return Kb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Lb;if(function(){return c.indexOf(Mb)!=-1}())return Nb;return Ob};t[Bb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};GWTPhotoAlbum_xs.onScriptLoad=function(a){GWTPhotoAlbum_xs.onScriptLoad=null;p=a;A()};if(z()){alert(Pb+Qb);return}C();B();n&&n({moduleName:N,sessionId:o,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:Rb});var H;try{F([Sb,Jb],Tb);F([vb,Jb],Tb);F([Ub,Jb],Tb);F([Sb,Cb],Vb);F([vb,Cb],Vb);F([Ub,Cb],Vb);F([Sb,Kb],Wb);F([vb,Kb],Wb);F([Ub,Kb],Wb);F([Sb,Lb],Xb);F([vb,Lb],Xb);F([Ub,Lb],Xb);F([Sb,Nb],Yb);F([vb,Nb],Yb);F([Ub,Nb],Yb);F([Sb,Hb],Zb);F([vb,Hb],Zb);F([Ub,Hb],Zb);H=v[G(ub)][G(Bb)];var I=H.indexOf($b);if(I!=-1){w=Number(H.substring(I+1));H=H.substring(0,I)}}catch(a){return}var J;function K(){if(!q){q=true;if(!__gwt_stylesLoaded[_b]){var a=m.createElement(ac);__gwt_stylesLoaded[_b]=a;a.setAttribute(bc,cc);a.setAttribute(dc,r+_b);m.getElementsByTagName(ec)[0].appendChild(a)}if(!__gwt_stylesLoaded[fc]){var a=m.createElement(ac);__gwt_stylesLoaded[fc]=a;a.setAttribute(bc,cc);a.setAttribute(dc,r+fc);m.getElementsByTagName(ec)[0].appendChild(a)}A();if(m.removeEventListener){m.removeEventListener(gc,K,false)}if(J){clearInterval(J)}}}
if(m.addEventListener){m.addEventListener(gc,function(){K()},false)}var J=setInterval(function(){if(/loaded|complete/.test(m.readyState)){K()}},50);n&&n({moduleName:N,sessionId:o,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:V});n&&n({moduleName:N,sessionId:o,subSystem:O,evtGroup:hc,millis:(new Date).getTime(),type:Q});var L=ic+r+H+jc;m.write(kc+lc+mc+nc+oc+pc+qc+nc+oc+rc+sc+tc+L+uc+vc+wc+xc)}
GWTPhotoAlbum_xs();