function GWTPhotoAlbum_xs(){var N='',uc='\n-',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hc='"<script src=\\"',gb='"><\/script>',X='#',zb='&',tc=');',lc='-\n',vc='-><\/scr',ec='../GWTPhotoAlbum.css',ic='.cache.js\\"><\/scr" + "ipt>"',Z='/',jb='//',Sb='2B606223EB89556804411A34AED58577',Ub='332ED162AFD0068A4B26FACD3032B2D1',Vb='7928D1629E4D25DAF2506E92DE39F989',Wb='7EF48FE6DF151A812CDAC7A6EC624CAD',Xb='8E368AF50F4FB637743F4835775F91A1',Zb=':',nb='::',jc='<scr',fb='<script id="',qb='=',Y='?',sb='Bad handler "',Ob='Cross-site hosted mode not yet implemented. See issue ',fc='DOMContentLoaded',Yb='F7250B84AE8B3872B807C98554404833',O='GWTPhotoAlbum_xs',cb='GWTPhotoAlbum_xs.nocache.js',mb='GWTPhotoAlbum_xs::',hb='SCRIPT',Cb='Unexpected exception in locale detection, using default: ',Bb='_',Ab='__gwt_Locale',eb='__gwt_marker_GWTPhotoAlbum_xs',ib='base',ab='baseUrl',R='begin',Q='bootstrap',_='clear.cache.gif',pb='content',Rb='de',xb='default',sc='document.write(',Tb='en',W='end',oc='evtGroup: "loadExternalRefs", millis:(new Date()).getTime(),',qc='evtGroup: "moduleStartup", millis:(new Date()).getTime(),',Lb='gecko',Mb='gecko1_8',S='gwt.codesvr=',T='gwt.hosted=',U='gwt.hybrid',$b='gwt/chrome/chrome.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',dc='head',cc='href',Pb='http://code.google.com/p/google-web-toolkit/issues/detail?id=2079',Kb='ie6',Jb='ie8',Ib='ie9',$='img',wc='ipt>',kc='ipt><!-',_b='link',gc='loadExternalRefs',wb='locale',yb='locale=',kb='meta',nc='moduleName:"GWTPhotoAlbum_xs", sessionId:window.__gwtStatsSessionId, subSystem:"startup",',V='moduleStartup',Hb='msie',lb='name',Eb='opera',ac='rel',Gb='safari',bb='script',Qb='selectingPermutation',P='startup',bc='stylesheet',pc='type: "end"});',rc='type: "moduleRequested"});',db='undefined',Nb='unknown',Db='user.agent',Fb='webkit',mc='window.__gwtStatsEvent && window.__gwtStatsEvent({';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s=N,t={},u=[],v=[],w=[],x=0,y,z;o&&o({moduleName:O,sessionId:p,subSystem:P,evtGroup:Q,millis:(new Date).getTime(),type:R});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=m.location.search;return (c.indexOf(S)!=-1||(c.indexOf(T)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(U)==-1}catch(a){}A=function(){return b};return b}
function B(){if(q&&r){q(y,O,s,x);o&&o({moduleName:O,sessionId:p,subSystem:P,evtGroup:V,millis:(new Date).getTime(),type:W})}}
function C(){function e(a){var b=a.lastIndexOf(X);if(b==-1){b=a.length}var c=a.indexOf(Y);if(c==-1){c=a.length}var d=a.lastIndexOf(Z,Math.min(c,b));return d>=0?a.substring(0,d+1):N}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement($);b.src=a+_;a=e(b.src)}return a}
function g(){var a=F(ab);if(a!=null){return a}return N}
function h(){var a=n.getElementsByTagName(bb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(cb)!=-1){return e(a[b].src)}}return N}
function i(){var a;if(typeof isBodyLoaded==db||!isBodyLoaded()){var b=eb;var c;n.write(fb+b+gb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=hb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return N}
function j(){var a=n.getElementsByTagName(ib);if(a.length>0){return a[a.length-1].href}return N}
function k(){var a=n.location;return a.href==a.protocol+jb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==N){l=h()}if(l==N){l=i()}if(l==N){l=j()}if(l==N&&k()){l=e(n.location.href)}l=f(l);s=l;return l}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,N);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=N}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
v[wb]=function(){var b=null;var c=xb;try{if(!b){var d=location.search;var e=d.indexOf(yb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(zb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(wb)}if(!b){b=m[Ab]}if(b){c=b}while(b&&!E(wb,b)){var h=b.lastIndexOf(Bb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Cb+a)}m[Ab]=c;return b||xb};u[wb]={de:0,'default':1,en:2};v[Db]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Eb)!=-1}())return Eb;if(function(){return b.indexOf(Fb)!=-1}())return Gb;if(function(){return b.indexOf(Hb)!=-1&&n.documentMode>=9}())return Ib;if(function(){return b.indexOf(Hb)!=-1&&n.documentMode>=8}())return Jb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Kb;if(function(){return b.indexOf(Lb)!=-1}())return Mb;return Nb};u[Db]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};GWTPhotoAlbum_xs.onScriptLoad=function(a){GWTPhotoAlbum_xs.onScriptLoad=null;q=a;B()};if(A()){alert(Ob+Pb);return}D();C();o&&o({moduleName:O,sessionId:p,subSystem:P,evtGroup:Q,millis:(new Date).getTime(),type:Qb});var I;try{G([Rb,Gb],Sb);G([xb,Gb],Sb);G([Tb,Gb],Sb);G([Rb,Kb],Ub);G([xb,Kb],Ub);G([Tb,Kb],Ub);G([Rb,Eb],Vb);G([xb,Eb],Vb);G([Tb,Eb],Vb);G([Rb,Ib],Wb);G([xb,Ib],Wb);G([Tb,Ib],Wb);G([Rb,Jb],Xb);G([xb,Jb],Xb);G([Tb,Jb],Xb);G([Rb,Mb],Yb);G([xb,Mb],Yb);G([Tb,Mb],Yb);I=w[H(wb)][H(Db)];var J=I.indexOf(Zb);if(J!=-1){x=Number(I.substring(J+1));I=I.substring(0,J)}}catch(a){return}var K;function L(){if(!r){r=true;if(!__gwt_stylesLoaded[$b]){var a=n.createElement(_b);__gwt_stylesLoaded[$b]=a;a.setAttribute(ac,bc);a.setAttribute(cc,s+$b);n.getElementsByTagName(dc)[0].appendChild(a)}if(!__gwt_stylesLoaded[ec]){var a=n.createElement(_b);__gwt_stylesLoaded[ec]=a;a.setAttribute(ac,bc);a.setAttribute(cc,s+ec);n.getElementsByTagName(dc)[0].appendChild(a)}B();if(n.removeEventListener){n.removeEventListener(fc,L,false)}if(K){clearInterval(K)}}}
if(n.addEventListener){n.addEventListener(fc,function(){L()},false)}var K=setInterval(function(){if(/loaded|complete/.test(n.readyState)){L()}},50);o&&o({moduleName:O,sessionId:p,subSystem:P,evtGroup:Q,millis:(new Date).getTime(),type:W});o&&o({moduleName:O,sessionId:p,subSystem:P,evtGroup:gc,millis:(new Date).getTime(),type:R});var M=hc+s+I+ic;n.write(jc+kc+lc+mc+nc+oc+pc+mc+nc+qc+rc+sc+M+tc+uc+vc+wc)}
GWTPhotoAlbum_xs();