function GWTPhotoAlbum_xs(){var Q='bootstrap',R='begin',S='gwt.codesvr.GWTPhotoAlbum_xs=',T='gwt.codesvr=',U='GWTPhotoAlbum_xs',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='javascript:""',_='position:absolute; width:0; height:0; border:none; left: -1000px;',ab=' top: -1000px;',bb='CSS1Compat',cb='<!doctype html>',db='',eb='<html><head><\/head><body><\/body><\/html>',fb='undefined',gb='DOMContentLoaded',hb=50,ib='Chrome',jb='eval("',kb='");',lb='script',mb='javascript',nb='moduleStartup',ob='moduleRequested',pb='Failed to load ',qb='head',rb='meta',sb='name',tb='GWTPhotoAlbum_xs::',ub='::',vb='gwt:property',wb='content',xb='=',yb='gwt:onPropertyErrorFn',zb='Bad handler "',Ab='" for "gwt:onPropertyErrorFn"',Bb='gwt:onLoadErrorFn',Cb='" for "gwt:onLoadErrorFn"',Db='#',Eb='?',Fb='/',Gb='img',Hb='clear.cache.gif',Ib='baseUrl',Jb='GWTPhotoAlbum_xs.nocache.js',Kb='base',Lb='//',Mb='locale',Nb='default',Ob='locale=',Pb=7,Qb='&',Rb='__gwt_Locale',Sb='_',Tb='Unexpected exception in locale detection, using default: ',Ub=2,Vb='user.agent',Wb='webkit',Xb='safari',Yb='msie',Zb=10,$b=11,_b='ie10',ac=9,bc='ie9',cc=8,dc='ie8',ec='gecko',fc='gecko1_8',gc=3,hc=4,ic='selectingPermutation',jc='GWTPhotoAlbum_xs.devmode.js',kc='de',lc='11D66C9748EC10D4C4CA091A3FFFB604',mc='en',nc='15C18263457AF276F3E8AE09D53BC3CC',oc='16EE72F249F01FEEDB8C9EDD374039EA',pc='3E58B97886705B230EBE60640FA93FFE',qc='46587F38EBAE199E5C92410ECF6A7454',rc='52E54E43D9D41C949B35438281505BC8',sc='538626EA8B66DFE7AD8724EB07B134ED',tc='562F7D396EF8D3EC24DD5B58D87D3778',uc='5C47D49AD78B5A331BDD7CE94981FC5C',vc='72F2B07D396AAC98E793821C8C7E80A5',wc='8314FC9F792F9F1CEA777110E88DBF51',xc='91DF860609FEE27E3736F1E77350C89A',yc='AD79831BF22F741DDAC3F5FE00BBB5D9',zc='DE1AC69DC24F8A31029FFC4769DF5497',Ac='EBA34FBB944260766A4EF5EB67458450',Bc=':',Cc='.cache.js',Dc='link',Ec='rel',Fc='stylesheet',Gc='href',Hc='loadExternalRefs',Ic='gwt/clean/clean.css',Jc='end',Kc='http:',Lc='file:',Mc='_gwt_dummy_',Nc='__gwtDevModeHook:GWTPhotoAlbum_xs',Oc='Ignoring non-whitelisted Dev Mode URL: ',Pc=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
GWTPhotoAlbum_xs.__sendStats=t;GWTPhotoAlbum_xs.__moduleName=U;GWTPhotoAlbum_xs.__errFn=null;GWTPhotoAlbum_xs.__moduleBase=W;GWTPhotoAlbum_xs.__softPermutationId=X;GWTPhotoAlbum_xs.__computePropValue=null;GWTPhotoAlbum_xs.__getPropMap=null;GWTPhotoAlbum_xs.__installRunAsyncCode=function(){};GWTPhotoAlbum_xs.__gwtStartLoadingFragment=function(){return null};GWTPhotoAlbum_xs.__gwt_isKnownPropertyValue=function(){return false};GWTPhotoAlbum_xs.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};GWTPhotoAlbum_xs.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[GWTPhotoAlbum_xs.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.src=$;a.id=U;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},hb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(jb));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(kb));g=e.createElement(lb);g.language=mb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(lb);g.language=mb;g.text=c[i];f.appendChild(g);d(f,g)}}}
GWTPhotoAlbum_xs.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;if(GWTPhotoAlbum_xs.__errFn){n.onerror=function(){GWTPhotoAlbum_xs.__errFn(U,new Error(pb+code))}}r.getElementsByTagName(qb)[X].appendChild(n)}
GWTPhotoAlbum_xs.__startLoadingFragment=function(a){return G(a)};GWTPhotoAlbum_xs.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(lb);d.language=mb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(rb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(sb),k;if(j){j=j.replace(tb,db);if(j.indexOf(ub)>=X){continue}if(j==vb){k=i.getAttribute(wb);if(k){var l,m=k.indexOf(xb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=db}c[j]=l}}else if(j==yb){k=i.getAttribute(wb);if(k){try{d=eval(k)}catch(a){alert(zb+k+Ab)}}}else if(j==Bb){k=i.getAttribute(wb);if(k){try{e=eval(k)}catch(a){alert(zb+k+Cb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;GWTPhotoAlbum_xs.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Db);if(b==-1){b=a.length}var c=a.indexOf(Eb);if(c==-1){c=a.length}var d=a.lastIndexOf(Fb,Math.min(c,b));return d>=X?a.substring(X,d+Y):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Gb);b.src=a+Hb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Ib);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(lb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Jb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Kb);if(a.length>X){return a[a.length-Y].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Lb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return GWTPhotoAlbum_xs.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Mb]=function(){var b=null;var c=Nb;try{if(!b){var d=location.search;var e=d.indexOf(Ob);if(e>=X){var f=d.substring(e+Pb);var g=d.indexOf(Qb,e);if(g<X){g=d.length}b=d.substring(e+Pb,g)}}if(!b){b=__gwt_getMetaProperty(Mb)}if(!b){b=q[Rb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Mb,b)){var h=b.lastIndexOf(Sb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Tb+a)}q[Rb]=c;return b||Nb};l[Mb]={de:X,'default':Y,en:Ub};m[Vb]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(Wb)!=-1}())return Xb;if(function(){return a.indexOf(Yb)!=-1&&(b>=Zb&&b<$b)}())return _b;if(function(){return a.indexOf(Yb)!=-1&&(b>=ac&&b<$b)}())return bc;if(function(){return a.indexOf(Yb)!=-1&&(b>=cc&&b<$b)}())return dc;if(function(){return a.indexOf(ec)!=-1||b>=$b}())return fc;return db};l[Vb]={gecko1_8:X,ie10:Y,ie8:Ub,ie9:gc,safari:hc};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};GWTPhotoAlbum_xs.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};GWTPhotoAlbum_xs.__computePropValue=n;q.__gwt_activeModules[U].bindings=GWTPhotoAlbum_xs.__getPropMap;t(Q,ic);if(s()){return G(jc)}var o;try{k([kc,_b],lc);k([mc,dc],nc);k([kc,dc],oc);k([Nb,fc],pc);k([mc,Xb],qc);k([Nb,Xb],rc);k([kc,Xb],sc);k([kc,bc],tc);k([Nb,bc],uc);k([kc,fc],vc);k([mc,fc],wc);k([Nb,dc],xc);k([mc,bc],yc);k([Nb,_b],zc);k([mc,_b],Ac);o=i[n(Mb)][n(Vb)];var p=o.indexOf(Bc);if(p!=-1){j=parseInt(o.substring(p+Y),Zb);o=o.substring(X,p)}}catch(a){}GWTPhotoAlbum_xs.__softPermutationId=j;return G(o+Cc)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(Dc);b.setAttribute(Ec,Fc);b.setAttribute(Gc,G(a));r.getElementsByTagName(qb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Hc,R);c(Ic);t(Hc,Jc)}
D();GWTPhotoAlbum_xs.__moduleBase=F();v[U].moduleBase=GWTPhotoAlbum_xs.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==Kc||q.location.protocol==Lc);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=Mc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=Nc;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(Oc+N)}N=db}if(N&&!q[M]){q[M]=true;q[M+Pc]=F();var O=r.createElement(lb);O.src=N;var P=r.getElementsByTagName(qb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,Jc);C(J);return true}
GWTPhotoAlbum_xs.succeeded=GWTPhotoAlbum_xs();